# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=255)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('plan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=255)),
                ('lname', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='tripmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_made', to='TripBuddy2APP3.User'),
        ),
    ]
