# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bday',
        ),
    ]
