# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegAPP', '0002_remove_user_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
