# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegAPP', '0004_auto_20191016_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postmessage', models.TextField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messagemaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_made', to='LoginAndRegAPP.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='messagemaker',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenttomessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_message', to='LoginAndRegAPP.PostMessage'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
