# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='default note', max_length=255),
            preserve_default=False,
        ),
    ]
